"""Nexus-LOB research layer (Part 2).

Pure functions over a ``View`` (the ``BOOK_STATE_DTYPE`` record as a dict)
plus forward labels, walk-forward datasets, and experiment/IC tooling.

Ground rules (plan_2.md §0) enforced here:
  * features are stateless pure functions of state at ``t`` — a test mutes the
    book after the call and asserts the feature is unchanged;
  * labels use prices strictly at ``t+h`` or later, never ``t``;
  * splits are walk-forward by calendar/sequence time, never shuffled CV.
"""
from .adverse_selection import (
    P_adverse,
    PassiveFill,
    adverse_groups,
    adverse_selection_report,
    drift_ticks,
    fills_from_tracker,
    filter_book_events,
    is_book_affecting,
    matched_unexecuted_control_drift,
    nw_tstat,
    p_adverse,
    p_adverse_unconditional,
    post_fill_drift,
    pre_fill_drift,
)
from .clock_markouts import (
    BOOTSTRAP_MIN_BLOCK_NS,
    CLOCK_HORIZONS_NS,
    E6_HEADLINE_H_EVENTS,
    LADDER_STAT,
    MEDIAN_LATTICE_NOTE,
    MID_LATTICE_PX0001,
    PX_UNIT_USD,
    REBATE_ASSUMPTION_NOTE,
    REBATE_SCENARIOS_PX0001,
    TICK_PX_UNITS,
    AggressorEvent,
    ClockFill,
    ClockFillCollector,
    MarkoutPanel,
    attribution_check,
    attribution_ladder,
    block_plan,
    clock_markout_report,
    clock_overlap_lag,
    event_time_markout,
    events_per_window,
    group_aggressor_events,
    group_masks,
    horizon_label,
    location_stats,
    markout_panel,
    markout_stats,
    raw_overlap,
    render_clock_markouts_md,
    sign_shares,
    trimmed_mean,
)
from .dataset import event_frame, make_split
from .experiments import (
    bootstrap_ci,
    brier_score,
    calibration_curve,
    decile_spread,
    diebold_mariano,
    hac_se,
    hit_rate,
    icir,
    normal_cdf,
    rank_ic,
    run_experiment,
)
from .features import (
    deep_imbalance,
    flow_intensity,
    lob_imbalance,
    microprice,
    momentum,
    ofi,
    realized_vol,
    spread_bps,
)
from .labels import forward_mid_move, forward_return
from .models import fit_ols_ic, zscore
from .multi_day_aggregation import (
    aggregate_multi_day_results,
    extract_day_study_record,
    extract_session_metrics,
    render_multi_day_aggregation_md,
    render_session_panel_md,
    session_panel_statistics,
)
from .queue_dynamics import (
    REGULAR_CLOSE_NS,
    REGULAR_OPEN_NS,
    EmpiricalQueueHazard,
    FillOutcome,
    FillRecord,
    FillRow,
    LogisticFillModel,
    OrderLevelTracker,
    OrderLife,
    QueueTracker,
    RestingOrder,
    StepFlow,
    TrackedOrder,
    calibration_table,
    censor_open_orders,
    compute_metrics,
    cumulative_incidence_competing_risks,
    fill_dataset,
    fill_prob_survival,
    filter_session_orders,
    logistic_fill_model,
    order_features,
    queue_ahead_walk,
    standing_order_lifetimes,
)
from .synthetic_flow import FLOW_PRESETS, FlowConfig, SyntheticFlow

__all__ = [
    "BOOTSTRAP_MIN_BLOCK_NS",
    "CLOCK_HORIZONS_NS",
    "E6_HEADLINE_H_EVENTS",
    "FLOW_PRESETS",
    "LADDER_STAT",
    "MEDIAN_LATTICE_NOTE",
    "MID_LATTICE_PX0001",
    "PX_UNIT_USD",
    "REBATE_ASSUMPTION_NOTE",
    "REBATE_SCENARIOS_PX0001",
    "REGULAR_CLOSE_NS",
    "REGULAR_OPEN_NS",
    "TICK_PX_UNITS",
    "AggressorEvent",
    "ClockFill",
    "ClockFillCollector",
    "EmpiricalQueueHazard",
    "FillOutcome",
    "FillRecord",
    "FillRow",
    "FlowConfig",
    "LogisticFillModel",
    "MarkoutPanel",
    "OrderLevelTracker",
    "OrderLife",
    "P_adverse",
    "PassiveFill",
    "QueueTracker",
    "RestingOrder",
    "StepFlow",
    "SyntheticFlow",
    "TrackedOrder",
    "adverse_groups",
    "adverse_selection_report",
    "aggregate_multi_day_results",
    "attribution_check",
    "attribution_ladder",
    "block_plan",
    "bootstrap_ci",
    "brier_score",
    "calibration_curve",
    "calibration_table",
    "censor_open_orders",
    "clock_markout_report",
    "clock_overlap_lag",
    "compute_metrics",
    "cumulative_incidence_competing_risks",
    "decile_spread",
    "deep_imbalance",
    "diebold_mariano",
    "drift_ticks",
    "event_frame",
    "event_time_markout",
    "events_per_window",
    "extract_day_study_record",
    "extract_session_metrics",
    "fill_dataset",
    "fill_prob_survival",
    "fills_from_tracker",
    "filter_book_events",
    "filter_session_orders",
    "fit_ols_ic",
    "flow_intensity",
    "forward_mid_move",
    "forward_return",
    "group_aggressor_events",
    "group_masks",
    "hac_se",
    "hit_rate",
    "horizon_label",
    "icir",
    "is_book_affecting",
    "lob_imbalance",
    "location_stats",
    "logistic_fill_model",
    "make_split",
    "markout_panel",
    "markout_stats",
    "matched_unexecuted_control_drift",
    "microprice",
    "momentum",
    "normal_cdf",
    "nw_tstat",
    "ofi",
    "order_features",
    "p_adverse",
    "p_adverse_unconditional",
    "post_fill_drift",
    "pre_fill_drift",
    "queue_ahead_walk",
    "rank_ic",
    "raw_overlap",
    "realized_vol",
    "render_clock_markouts_md",
    "render_multi_day_aggregation_md",
    "render_session_panel_md",
    "run_experiment",
    "session_panel_statistics",
    "sign_shares",
    "spread_bps",
    "standing_order_lifetimes",
    "trimmed_mean",
    "zscore",
]
